# Generated by Django 3.1.1 on 2020-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
