# Generated by Django 3.1.1 on 2020-09-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_benefits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benefits',
            new_name='Benefit',
        ),
    ]
