# Generated by Django 3.1.1 on 2020-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0006_auto_20200902_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='practice',
            new_name='meditation',
        ),
    ]
