# Generated by Django 3.1.1 on 2020-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_meditation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='benefit',
            field=models.TextField(),
        ),
    ]
